// <auto-generated />
using System;
using Demodha.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demodha.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260105025109_userprofile")]
    partial class userprofile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demodha.Data.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Demodha.Data.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActivationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("File_Number")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LastName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("User_CNIC")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("User_CNIC", "File_Number")
                        .IsUnique()
                        .HasFilter("[User_CNIC] IS NOT NULL AND [File_Number] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Demodha.Models.Dealer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Dealers");
                });

            modelBuilder.Entity("Demodha.Models.NdcApplication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte>("CurrentStage")
                        .HasColumnType("tinyint");

                    b.Property<byte>("CurrentStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("DealerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PlotOrFileNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SectorOrPhase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SocietyOrScheme")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DealerUserId");

                    b.HasIndex("PlotOrFileNo", "Block", "SectorOrPhase", "SocietyOrScheme");

                    b.ToTable("NdcApplications");
                });

            modelBuilder.Entity("Demodha.Models.NdcAppointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("NdcApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("NotifiedDealer")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifiedOwner")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NdcApplicationId")
                        .IsUnique();

                    b.ToTable("NdcAppointments");
                });

            modelBuilder.Entity("Demodha.Models.NdcClearance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CompletionCertificateDocumentId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Department")
                        .HasColumnType("tinyint");

                    b.Property<long>("NdcApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReviewedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ReviewedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CompletionCertificateDocumentId");

                    b.HasIndex("NdcApplicationId", "Department")
                        .IsUnique();

                    b.ToTable("NdcClearances");
                });

            modelBuilder.Entity("Demodha.Models.NdcDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("DocType")
                        .HasColumnType("tinyint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<long>("NdcApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerifiedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("VerifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NdcApplicationId", "DocType");

                    b.ToTable("NdcDocuments");
                });

            modelBuilder.Entity("Demodha.Models.NdcFinanceCase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChallanDocumentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ChallanGeneratedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedChallanNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("NdcApplicationId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("OutstandingAmount")
                        .HasColumnType("decimal(19,2)");

                    b.Property<long?>("PaymentReceiptDocumentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PaymentReceived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaymentReceivedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChallanDocumentId");

                    b.HasIndex("NdcApplicationId")
                        .IsUnique();

                    b.HasIndex("PaymentReceiptDocumentId");

                    b.ToTable("NdcFinanceCases");
                });

            modelBuilder.Entity("Demodha.Models.NdcParty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CNIC")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("NdcApplicationId")
                        .HasColumnType("bigint");

                    b.Property<byte>("PartyType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("NdcApplicationId", "PartyType")
                        .IsUnique();

                    b.ToTable("NdcParties");
                });

            modelBuilder.Entity("Demodha.Models.NdcStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ActionOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("FromStage")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("FromStatus")
                        .HasColumnType("tinyint");

                    b.Property<long>("NdcApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("ToStage")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ToStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("NdcApplicationId", "ActionOn");

                    b.ToTable("NdcStatusHistories");
                });

            modelBuilder.Entity("Demodha.Models.NdcTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CompletedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<long>("NdcApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TaskDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskDefinitionId");

                    b.HasIndex("NdcApplicationId", "TaskDefinitionId")
                        .IsUnique();

                    b.ToTable("NdcTasks");
                });

            modelBuilder.Entity("Demodha.Models.NdcTaskDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<byte>("Stage")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Stage", "SortOrder");

                    b.ToTable("NdcTaskDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsMandatory = true,
                            SortOrder = 1,
                            Stage = (byte)1,
                            Title = "Fill NDC Application"
                        },
                        new
                        {
                            Id = 2,
                            IsMandatory = true,
                            SortOrder = 2,
                            Stage = (byte)1,
                            Title = "Attach 2x Photographs"
                        },
                        new
                        {
                            Id = 3,
                            IsMandatory = true,
                            SortOrder = 3,
                            Stage = (byte)1,
                            Title = "Attach Copy of CNIC"
                        },
                        new
                        {
                            Id = 4,
                            IsMandatory = true,
                            SortOrder = 4,
                            Stage = (byte)1,
                            Title = "Attach Application to Secretary DHAG (Seller)"
                        },
                        new
                        {
                            Id = 5,
                            IsMandatory = true,
                            SortOrder = 5,
                            Stage = (byte)1,
                            Title = "Save and Submit to Dealer"
                        },
                        new
                        {
                            Id = 6,
                            IsMandatory = true,
                            SortOrder = 1,
                            Stage = (byte)2,
                            Title = "Check NDC Application"
                        },
                        new
                        {
                            Id = 7,
                            IsMandatory = true,
                            SortOrder = 2,
                            Stage = (byte)2,
                            Title = "Payment Challan Form"
                        },
                        new
                        {
                            Id = 8,
                            IsMandatory = true,
                            SortOrder = 3,
                            Stage = (byte)2,
                            Title = "Attach Seller Consent Form"
                        },
                        new
                        {
                            Id = 9,
                            IsMandatory = true,
                            SortOrder = 4,
                            Stage = (byte)2,
                            Title = "Attach Purchaser Consent Form"
                        },
                        new
                        {
                            Id = 10,
                            IsMandatory = true,
                            SortOrder = 5,
                            Stage = (byte)2,
                            Title = "Save and Submit to Transfer Br"
                        },
                        new
                        {
                            Id = 11,
                            IsMandatory = true,
                            SortOrder = 1,
                            Stage = (byte)3,
                            Title = "Check NDC Application Form"
                        },
                        new
                        {
                            Id = 12,
                            IsMandatory = true,
                            SortOrder = 2,
                            Stage = (byte)3,
                            Title = "Check Payment Challan Form"
                        },
                        new
                        {
                            Id = 13,
                            IsMandatory = true,
                            SortOrder = 3,
                            Stage = (byte)3,
                            Title = "Check Seller Consent Form"
                        },
                        new
                        {
                            Id = 14,
                            IsMandatory = true,
                            SortOrder = 4,
                            Stage = (byte)3,
                            Title = "Check Purchaser Consent Form"
                        },
                        new
                        {
                            Id = 15,
                            IsMandatory = true,
                            SortOrder = 5,
                            Stage = (byte)3,
                            Title = "Check e-Stamp Paper verification"
                        },
                        new
                        {
                            Id = 16,
                            IsMandatory = true,
                            SortOrder = 6,
                            Stage = (byte)3,
                            Title = "Send for clearances (Record, Legal, Land, Plans, BC, Fin)"
                        },
                        new
                        {
                            Id = 17,
                            IsMandatory = true,
                            SortOrder = 1,
                            Stage = (byte)5,
                            Title = "Call Owner & Dealer for NDC issuance/handover schedule"
                        },
                        new
                        {
                            Id = 18,
                            IsMandatory = true,
                            SortOrder = 1,
                            Stage = (byte)6,
                            Title = "Check all documents"
                        },
                        new
                        {
                            Id = 19,
                            IsMandatory = true,
                            SortOrder = 2,
                            Stage = (byte)6,
                            Title = "Undergo NADRA ID Card Verisys"
                        },
                        new
                        {
                            Id = 20,
                            IsMandatory = true,
                            SortOrder = 3,
                            Stage = (byte)6,
                            Title = "Dealer provided original documents"
                        },
                        new
                        {
                            Id = 21,
                            IsMandatory = true,
                            SortOrder = 4,
                            Stage = (byte)6,
                            Title = "Seller & purchaser finger/biometric verification (PMS/NADRA)"
                        },
                        new
                        {
                            Id = 22,
                            IsMandatory = true,
                            SortOrder = 5,
                            Stage = (byte)6,
                            Title = "Transfer office recheck all details"
                        },
                        new
                        {
                            Id = 23,
                            IsMandatory = true,
                            SortOrder = 6,
                            Stage = (byte)6,
                            Title = "e-Stamp paper verification"
                        },
                        new
                        {
                            Id = 24,
                            IsMandatory = true,
                            SortOrder = 7,
                            Stage = (byte)6,
                            Title = "Execute Transfer"
                        });
                });

            modelBuilder.Entity("Demodha.Models.NdcVerification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EStampRefNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EStampVerificationStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NadraCheckedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NadraCheckedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NadraCnicVerisysStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("NdcApplicationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("OriginalDocsReceived")
                        .HasColumnType("bit");

                    b.Property<string>("PmsFingerVerificationStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PurchaserBiometricStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SellerBiometricStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("TransferOfficeRecheckDone")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NdcApplicationId")
                        .IsUnique();

                    b.ToTable("NdcVerifications");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Demodha.Models.NdcApplication", b =>
                {
                    b.HasOne("Demodha.Data.Identity.ApplicationUser", "DealerUser")
                        .WithMany()
                        .HasForeignKey("DealerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DealerUser");
                });

            modelBuilder.Entity("Demodha.Models.NdcAppointment", b =>
                {
                    b.HasOne("Demodha.Models.NdcApplication", "NdcApplication")
                        .WithOne("Appointment")
                        .HasForeignKey("Demodha.Models.NdcAppointment", "NdcApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NdcApplication");
                });

            modelBuilder.Entity("Demodha.Models.NdcClearance", b =>
                {
                    b.HasOne("Demodha.Models.NdcDocument", "CompletionCertificateDocument")
                        .WithMany()
                        .HasForeignKey("CompletionCertificateDocumentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Demodha.Models.NdcApplication", "NdcApplication")
                        .WithMany("Clearances")
                        .HasForeignKey("NdcApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletionCertificateDocument");

                    b.Navigation("NdcApplication");
                });

            modelBuilder.Entity("Demodha.Models.NdcDocument", b =>
                {
                    b.HasOne("Demodha.Models.NdcApplication", "NdcApplication")
                        .WithMany("Documents")
                        .HasForeignKey("NdcApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NdcApplication");
                });

            modelBuilder.Entity("Demodha.Models.NdcFinanceCase", b =>
                {
                    b.HasOne("Demodha.Models.NdcDocument", "ChallanDocument")
                        .WithMany()
                        .HasForeignKey("ChallanDocumentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Demodha.Models.NdcApplication", "NdcApplication")
                        .WithOne("FinanceCase")
                        .HasForeignKey("Demodha.Models.NdcFinanceCase", "NdcApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demodha.Models.NdcDocument", "PaymentReceiptDocument")
                        .WithMany()
                        .HasForeignKey("PaymentReceiptDocumentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ChallanDocument");

                    b.Navigation("NdcApplication");

                    b.Navigation("PaymentReceiptDocument");
                });

            modelBuilder.Entity("Demodha.Models.NdcParty", b =>
                {
                    b.HasOne("Demodha.Models.NdcApplication", "NdcApplication")
                        .WithMany("Parties")
                        .HasForeignKey("NdcApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NdcApplication");
                });

            modelBuilder.Entity("Demodha.Models.NdcStatusHistory", b =>
                {
                    b.HasOne("Demodha.Models.NdcApplication", "NdcApplication")
                        .WithMany("StatusHistory")
                        .HasForeignKey("NdcApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NdcApplication");
                });

            modelBuilder.Entity("Demodha.Models.NdcTask", b =>
                {
                    b.HasOne("Demodha.Models.NdcApplication", "NdcApplication")
                        .WithMany("Tasks")
                        .HasForeignKey("NdcApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demodha.Models.NdcTaskDefinition", "TaskDefinition")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NdcApplication");

                    b.Navigation("TaskDefinition");
                });

            modelBuilder.Entity("Demodha.Models.NdcVerification", b =>
                {
                    b.HasOne("Demodha.Models.NdcApplication", "NdcApplication")
                        .WithOne("Verification")
                        .HasForeignKey("Demodha.Models.NdcVerification", "NdcApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NdcApplication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Demodha.Data.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Demodha.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Demodha.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Demodha.Data.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demodha.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Demodha.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Demodha.Models.NdcApplication", b =>
                {
                    b.Navigation("Appointment");

                    b.Navigation("Clearances");

                    b.Navigation("Documents");

                    b.Navigation("FinanceCase");

                    b.Navigation("Parties");

                    b.Navigation("StatusHistory");

                    b.Navigation("Tasks");

                    b.Navigation("Verification");
                });

            modelBuilder.Entity("Demodha.Models.NdcTaskDefinition", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
